name:                http-link-header
version:             1.2.1
synopsis:            A parser and writer for the HTTP Link header per RFC 5988
category:            Web
github:              myfreeweb/http-link-header
license:             PublicDomain
license-file:        UNLICENSE
author:              Greg V
maintainer:          stevenjshuck@gmail.com
copyright:           2014-2021 Greg V <greg@unrelenting.technology>

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/myfreeweb/http-link-header#readme>

build-type:          Simple

dependencies:
- base >= 4.3 && < 5
- attoparsec
- bytestring
- errors
- http-api-data
- network-uri
- text

library:
  source-dirs: library
  ghc-options:
  - -Wall

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test-suite
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - http-link-header
    - hspec
    - hspec-attoparsec
    - QuickCheck

benchmarks:
  benchmarks:
    main:                Bench.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - http-link-header
    - directory
    - transformers
    - criterion
